name: SManage
main: net.devsong.smanage.SManage
version: 5.1
author: Devsong
load: STARTUP
description: 管理生物生成速度 Manage creatures' spawning speed
commands:
  smanage:
    aliases: sm
    description: SManage插件命令 SManage plugin commands
    usage: /smanage help
permissions:
  smanage.edit:
    description: 编辑区域所需的权限 Edit the permissions required for the regions.
    default: op
  smanage.read:
    description: 查看区域相关信息所需的权限 Permissions required to view relevant information.
    default: true