name: SLimit
main: net.devsong.slimit.SLimit
version: 2.3
author: Devsong
load: STARTUP
description: 区域限制生物生成
commands:
  slimit:
    description: SLimit插件命令
    usage: /slimit
    permission: slimit.read
    permission-message: 你没有权限这么做
  slimit reload:
    description: 重新加载 SLimit配置文件
    usage: /slimit reload
    permission: slimit.edit
    permission-message: 你没有权限这么做
  slimit set:
    description: 设置一个区域
    usage: /slimit set <NAME>
    permission: slimit.edit
    permission-message: 你没有权限这么做
  slimit save:
    description: 保存已更改的区域
    usage: /slimit save
    permission: slimit.edit
    permission-message: 你没有权限这么做
  slimit cancel:
    description: 取消本次新建/修改区域
    usage: /slimit cancel
    permission: slimit.edit
    permission-message: 你没有权限这么做
  slimit list:
    description: 查看已保存的区域
    usage: /slimit list
    permission: slimit.read
    permission-message: 你没有权限这么做
  slimit detail:
    description: 查看某个区域的详情
    usage: /slimit detail <NAME>
    permission: slimit.read
    permission-message: 你没有权限这么做
  slimit remove:
    description: 删除某个区域
    usage: /slimit remove <NAME>
    permission: slimit.edit
    permission-message: 你没有权限这么做
  slimit setMonSpeed:
    description: 设置单个区域怪物生成速度
    usage: /slimit setMonSpeed <NAME> <NUMBER>
    permission: slimit.edit
    permission-message: 你没有权限这么做
  slimit setALLMonSpeed:
    description: 设置所有区域怪物生成速度
    usage: /slimit setALLMonSpeed <NUMBER>
    permission: slimit.edit
    permission-message: 你没有权限这么做
  slimit setAniSpeed:
    description: 设置单个区域动物生成速度
    usage: /slimit setAniSpeed <NAME> <NUMBER>
    permission: slimit.edit
    permission-message: 你没有权限这么做
  slimit setALLAniSpeed:
    description: 设置所有区域动物生成速度
    usage: /slimit setALLAniSpeed <NUMBER>
    permission: slimit.edit
    permission-message: 你没有权限这么做
  slimit setter:
    description: 设置划定区域的物品
    usage: /slimit setter
    permission: slimit.edit
    permission-message: 你没有权限这么做
  slimit help:
    description: 查看SLimit插件使用说明
    usage: /slimit help
    permission: slimit.read
    permission-message: 你没有权限这么做
permissions:
  slimit.edit:
    description: 编辑区域所需的权限
    default: op
  slimit.read:
    description: 查看区域相关信息所需的权限
    default: true