name: SManage
main: net.devsong.smanage.SManage
version: 3.4
author: Devsong
load: STARTUP
description: 区域管理生物生成
commands:
  smanage:
    description: SManage插件命令
    usage: /smanage
    permission: smanage.read
    permission-message: 你没有权限这么做
  sm:
    description: SManage插件命令
    usage: /sm
    permission: smanage.read
    permission-message: 你没有权限这么做
permissions:
  smanage.edit:
    description: 编辑区域所需的权限
    default: op
  smanage.read:
    description: 查看区域相关信息所需的权限
    default: true