name: SManage
main: net.devsong.smanage.SManage
version: 4.0
author: Devsong
load: STARTUP
description: 区域管理生物生成
commands:
  smanage:
    aliases: sm
    description: SManage插件命令
    usage: /smanage help
permissions:
  smanage.edit:
    description: 编辑区域所需的权限
    default: op
  smanage.read:
    description: 查看区域相关信息所需的权限
    default: true